### ISSUE TITLE
他人の質問・回答を更新・削除出来てしまう

### ISSUE THREAD

**Issue by shogo-mitomo** [shogo-mitomo/burary-shimane#17]
- 以下の2つの対応が必要かと
  1. フロントサイドで他人の質問回答にはボタンを表示しないようにする
  2. サーバーサイドで制限をかける

**Comment by Ryoma-h777** [comment]
編集済み。完璧ではないと思うので、後で確認のテストなど行う。

**Comment by Ryoma-h777** [comment]
question一覧にを見る際に、ログインしてなくてもcurrent_use.idが使われているので修正が必要

**Comment by Ryoma-h777** [comment]
修正済み
(変更前)if current_user.id == @question.user_id 
(変更後)if **user_signed_in? &&** current_user.id == @question.user_id
