### ISSUE TITLE
ゲストユーザーでの利用を想定した実装となっていない

### ISSUE THREAD

**Issue by shogo-mitomo** [shogo-mitomo/burary-shimane#18]
- アカウントがないと質問・回答の作成時にエラーになってしまう

![error](https://cloud.githubusercontent.com/assets/11454525/18237028/75e209ae-7367-11e6-83a9-2a42e9b3b2c7.png)

**Comment by Ryoma-h777** [comment]
参考になりそうなサイト
http://ruby-rails.hatenadiary.com/entry/20141212/1418380288
