### ISSUE TITLE
バリデーションを追加する

### ISSUE THREAD

**Issue by shogo-mitomo** [shogo-mitomo/burary-shimane#23]
- 現状だと全項目空で質問が作成できてしまう
  - データベースに制約を追加する（物理的に保存出来なくする）
  - Railsレベルでのバリデーションを追加する（エラーメッセージなどがハンドリングできる）

![validation](https://cloud.githubusercontent.com/assets/11454525/18246238/68f1be86-73a5-11e6-901d-35195ee7ee3e.png)

**Comment by Ryoma-h777** [comment]
参考にしたサイト
http://ruby-rails.hatenadiary.com/entry/20140724/1406145303

現状で
question.rb　タイトルと内容が空白だとクリエイトできない。
:title, presence: true
:contents, presence: true

answer.rb　回答の詳細が空白だとクリエイトできない。
spot_detail, presence: true

さらにDBの方でも空を受け付けないように変更
※db:migrateしてください！
